### PR TITLE
Add Pyraminx L3E

### PR DESCRIPTION
**Pull request by OWelton-Rosie**

### CODE REVIEW

**Comment by spencerchubb** [comment]
@OWelton-Rosie I need to implement a visualizer for pyraminx and as soon as I do that, I can merge this in

**Comment by OWelton-Rosie** [comment]
> @OWelton-Rosie I need to implement a visualizer for pyraminx and as soon as I do that, I can merge this in

Sweet as! No rush. It'll take me a little while to write another json for L4E anyways.

**Comment by spencerchubb** [comment]
making progress, got the basic shape down :)
{18E9A66B-0305-4CBF-8687-7D0C3558AA75}

**Comment by OWelton-Rosie** [comment]
Awesome! Glad to see it went through. If there's something I did wrong, please let me know.

**Pull request merged**
